# Generated by Django 3.1.7 on 2021-03-27 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20210326_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-subject']},
        ),
    ]
