# Generated by Django 3.1.7 on 2021-03-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20210327_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='module',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
