# Generated by Django 3.1.7 on 2021-03-27 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20210327_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='following',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
