# Generated by Django 3.1.7 on 2021-03-29 04:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_auto_20210327_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewerprofile',
            name='following',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
