# Generated by Django 3.1.7 on 2021-03-31 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_auto_20210329_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='cfollower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='cfollowing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viewerprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='vfollowing', to=settings.AUTH_USER_MODEL),
        ),
    ]
